### ISSUE TITLE
Composite Address PDF issue

### ISSUE THREAD

**Issue by amback00** [a33ik/CompositeAddress_PCF#1]
The "Bind to a value on a field" drop-down for the Composite Address control does not work. When attempted to choose "Address 1: Street 1" for binding the "Street 1" control setup, the "Address 1: Street 1" field is not available to choose.
![Composite Address Control issue1](https://user-images.githubusercontent.com/40772665/66721088-8f059900-edd0-11e9-990a-d91d07b25619.png)
![Composite Address Control issue2](https://user-images.githubusercontent.com/40772665/66721095-92992000-edd0-11e9-8bef-e8ffea1af4f5.png)

**Comment by AndrewButenko** [comment]
Hello,
This is a bug but not in my control but in Dynamics 365 - https://www.magnetismsolutions.com/blog/jaredjohnson/2019/07/04/binding-to-address-fields-in-a-pcf-control
It's possible to bind control to those fields but you will have to do it manually until it's fixed by Microsoft.

Closing the issue,
Andrew

**Comment by amback00** [comment]
Thanks Andrew for the follow up.

Thanks,
Aaron Back

________________________________

**Comment by AndrewButenko** [comment]
Aaron,
You are welcome! If you have any other feedback regarding the control feel free to share it.
Thanks,
Andrew

**Comment by SyvokonSergey** [comment]
Thx, Andrew,
You did a great job

BR
Sergey
